#!/usr/bin/env bash
# gen-config.sh — renders the Fuseki deployment files from ../kg.config.yaml:
#   .env                      (compose interpolation values: project, port, ...)
#   config-<dataset>.ttl      (Fuseki assembler config for the dataset)
# Run after editing kg.config.yaml, before `docker compose up -d`.
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
source "$HERE/../scripts/kg-env.sh"

cat > "$HERE/.env" <<EOF
# GENERATED by gen-config.sh from kg.config.yaml — do not edit by hand.
KG_COMPOSE_PROJECT=$KG_COMPOSE_PROJECT
KG_CONTAINER_NAME=$KG_CONTAINER_NAME
KG_FUSEKI_PORT=$KG_FUSEKI_PORT
KG_FUSEKI_PASS=$KG_FUSEKI_PASS
KG_FUSEKI_DATASET=$KG_FUSEKI_DATASET
EOF

CFG="$HERE/config-$KG_FUSEKI_DATASET.ttl"
cat > "$CFG" <<EOF
# GENERATED by gen-config.sh from kg.config.yaml — do not edit by hand.
#
# Fuseki assembler config for the \`$KG_FUSEKI_DATASET\` dataset WITH query-time reasoning.
#
# Wraps an in-memory base model in an OWLMicro inference model. OWLMicro
# materializes: rdfs:subClassOf / subPropertyOf, domain/range, owl:inverseOf,
# owl:SymmetricProperty, owl:TransitiveProperty, sameAs. That makes the rules
# in the authored vocabulary modules visible at query time — e.g. a symmetric
# integrates-with relation and inverse property pairs are inferred, and
# upstream-typed individuals are recognised under their superclasses.
#
# The store is in-memory and repopulated by scripts/rebuild.sh (or
# load-fuseki.sh) from the wiki Turtle — the wiki is the system of record,
# Fuseki is a derived query surface. Deep contradiction checking is done at
# build/ingestion time with HermiT (see scripts/validate-ingestion.sh), not
# here; this reasoner is for query-time entailment.

@prefix :        <#> .
@prefix fuseki:  <http://jena.apache.org/fuseki#> .
@prefix ja:      <http://jena.hpl.hp.com/2005/11/Assembler#> .
@prefix rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs:    <http://www.w3.org/2000/01/rdf-schema#> .

:service a fuseki:Service ;
    fuseki:name "$KG_FUSEKI_DATASET" ;
    fuseki:endpoint [ fuseki:operation fuseki:query ] ;
    fuseki:endpoint [ fuseki:operation fuseki:query  ; fuseki:name "sparql" ] ;
    fuseki:endpoint [ fuseki:operation fuseki:query  ; fuseki:name "query" ] ;
    fuseki:endpoint [ fuseki:operation fuseki:update ; fuseki:name "update" ] ;
    fuseki:endpoint [ fuseki:operation fuseki:gsp-rw ; fuseki:name "data" ] ;
    fuseki:endpoint [ fuseki:operation fuseki:gsp-r  ; fuseki:name "get" ] ;
    fuseki:dataset :dataset .

:dataset a ja:RDFDataset ;
    ja:defaultGraph :infModel .

:infModel a ja:InfModel ;
    ja:baseModel [ a ja:MemoryModel ] ;
    ja:reasoner [
        ja:reasonerURL <http://jena.hpl.hp.com/2003/OWLMicroFBRuleReasoner>
    ] .
EOF

echo "✓ wrote $HERE/.env"
echo "✓ wrote $CFG"
