#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ONTOLOGY_DIR="$SCRIPT_DIR/../ontology"
ROBOT="$SCRIPT_DIR/robot"
EXTRACTS="$ONTOLOGY_DIR/extracts"
SEEDS="$ONTOLOGY_DIR/seeds"

mkdir -p "$EXTRACTS"

extract() {
  local name="$1"
  local source_url="$2"
  local seed_file="$SEEDS/$name-seeds.txt"

  if [ ! -s "$seed_file" ]; then
    echo "▶ Skipping $name — $seed_file is empty (nothing in our own TTL references this vocabulary right now)"
    rm -f "$EXTRACTS/$name-module.ttl"
    return
  fi

  echo "▶ Extracting $name from $source_url"
  "$ROBOT" extract \
    --input-iri "$source_url" \
    --method MIREOT \
    --lower-terms "$seed_file" \
    --output "$EXTRACTS/$name-module.ttl"

  echo "✓ $EXTRACTS/$name-module.ttl"
}

# Seed files are generated by gen-seeds.py from what our own ontology/wiki
# TTL actually references — not hand-maintained. Run it before this script
# (rebuild.sh does this automatically) so a newly-adopted upstream term is
# picked up on the next rebuild instead of silently going stale.
extract org    "http://www.w3.org/ns/org"
extract prov   "http://www.w3.org/ns/prov-o"
extract foaf   "http://xmlns.com/foaf/spec/index.rdf"
extract skos   "http://www.w3.org/2004/02/skos/core"
extract schema "https://schema.org/version/latest/schemaorg-current-https.ttl"
extract time   "https://www.w3.org/2006/time"
extract dct    "http://purl.org/dc/terms/"

# FIBO is large and modular — each namespace below is a distinct FIBO
# sub-ontology, pulled from its own module.
extract fibo-fbc-fct-fse \
  "https://spec.edmcouncil.org/fibo/ontology/master/latest/FBC/FunctionalEntities/FinancialServicesEntities/"
extract fibo-fnd-utl-alx \
  "https://spec.edmcouncil.org/fibo/ontology/master/latest/FND/Utilities/Analytics/"

# VCR-0020 (2026-07-07): ownership alignment (EntityOwnership/hasOwningEntity) +
# legal-form adoption (EntityLegalForm/hasLegalForm), both Business Entities (BE) modules.
extract fibo-be-oc-op \
  "https://spec.edmcouncil.org/fibo/ontology/master/latest/BE/OwnershipAndControl/OwnershipParties/"
extract fibo-be-le-lei \
  "https://spec.edmcouncil.org/fibo/ontology/master/latest/BE/LegalEntities/LEIEntities/"

echo "All extractions complete."
