#!/usr/bin/env python3
"""gen-schema-concepts.py — compiles wiki/_schema/{domains,subcategories,tags}.md
(the wiki's controlled vocabulary of record) into SKOS concept schemes at
ontology/seeds/schema-concepts.ttl (VCR-0002).

wiki/_schema stays the human source of truth; this generator makes the same
controlled vocabulary first-class graph citizens so frontmatter values are
queryable and SHACL-checkable. Re-run after any approved schema addition —
the apply step of a proposal with a "Schema / vocabulary additions" section
must run this and commit the regenerated seed file alongside the .md change.

IRIs: aiw:domain-<slug>, aiw:subcategory-<slug>, aiw:tag-<slug> — prefixed so
they can never collide with page-slug IRIs (aiw:<page-slug>). Permanent.

Usage: python3 gen-schema-concepts.py
"""
import os
import re
import sys

import kgconfig

C = kgconfig.cfg()
SCHEMA_DIR = os.path.join(C["_wiki_dir"], "_schema")
OUT = os.path.join(C["_ontology_dir"], "seeds", "schema-concepts.ttl")
PREFIX = kgconfig.prefix()

BULLET = re.compile(r"^- \*\*`([a-z0-9-]+)`\*\*\s*[—–-]\s*(.+)$")


def esc(s):
    return s.replace("\\", "\\\\").replace('"', '\\"').strip()


def parse_bullets(path, section_heading):
    """- **`slug`** — description   bullets inside the given ## section."""
    out = []
    in_section = False
    for line in open(path):
        if line.startswith("## "):
            in_section = line.strip() == section_heading
            continue
        if in_section:
            m = BULLET.match(line.strip())
            if m:
                out.append((m.group(1), m.group(2)))
    return out


def parse_subcategories(path):
    """### slug sections with '- **Parent domain(s):** a, b' and '- **Definition:** ...'."""
    out = []
    slug, parents, definition = None, [], None
    def flush():
        if slug:
            out.append((slug, parents, definition))
    for line in open(path):
        line = line.rstrip()
        if line.startswith("### "):
            flush()
            cand = line[4:].strip().strip("`")
            # only slug-shaped headings are subcategories; prose sections
            # ("Format", "Adding a new subcategory") are not
            slug, parents, definition = (cand if re.fullmatch(r"[a-z0-9-]+", cand) else None), [], None
        elif slug and line.strip().startswith("- **Parent domain(s):**"):
            raw = line.split("**Parent domain(s):**", 1)[1]
            parents = [p.strip().strip("`") for p in raw.split(",") if p.strip()]
        elif slug and line.strip().startswith("- **Definition:**"):
            definition = line.split("**Definition:**", 1)[1].strip()
    flush()
    return out


def main():
    domains = parse_bullets(os.path.join(SCHEMA_DIR, "domains.md"), "## Current domains")
    tags = parse_bullets(os.path.join(SCHEMA_DIR, "tags.md"), "## Current tags")
    subcats = parse_subcategories(os.path.join(SCHEMA_DIR, "subcategories.md"))
    if not domains or not tags or not subcats:
        sys.exit(f"✗ parse failure: domains={len(domains)} tags={len(tags)} subcategories={len(subcats)}")

    domain_slugs = {s for s, _ in domains}
    lines = [
        "# GENERATED by scripts/gen-schema-concepts.py from wiki/_schema/*.md — do not edit by hand.",
        "# Regenerate after any approved schema (domain/subcategory/tag) addition. VCR-0002.",
        f"@prefix {PREFIX}: <{kgconfig.data_iri()}> .",
        "@prefix skos: <http://www.w3.org/2004/02/skos/core#> .",
        "",
        f"{PREFIX}:domain-scheme a skos:ConceptScheme ;",
        '    skos:prefLabel "AI Wiki domains"@en ;',
        '    skos:definition "High-level areas of use; the controlled vocabulary behind the frontmatter domains: field (wiki/_schema/domains.md)."@en .',
        "",
        f"{PREFIX}:subcategory-scheme a skos:ConceptScheme ;",
        '    skos:prefLabel "AI Wiki subcategories"@en ;',
        '    skos:definition "Cohorts of comparable tools/models/workflows; the controlled vocabulary behind the frontmatter subcategory: field (wiki/_schema/subcategories.md)."@en .',
        "",
        f"{PREFIX}:tag-scheme a skos:ConceptScheme ;",
        '    skos:prefLabel "AI Wiki tags"@en ;',
        '    skos:definition "Cross-cutting attributes (vendor, license, ecosystem, flavor); the controlled vocabulary behind the frontmatter tags: field (wiki/_schema/tags.md)."@en .',
        "",
    ]
    for slug, desc in domains:
        lines += [
            f"{PREFIX}:domain-{slug} a skos:Concept ;",
            f'    skos:prefLabel "{esc(slug)}"@en ;',
            f'    skos:definition "{esc(desc)}"@en ;',
            f'    skos:notation "{esc(slug)}" ;',
            f"    skos:inScheme {PREFIX}:domain-scheme .",
            "",
        ]
    for slug, parents, definition in subcats:
        if not definition:
            print(f"  ! subcategory {slug} has no Definition — using placeholder")
            definition = f"Subcategory {slug} (definition missing in wiki/_schema/subcategories.md)."
        lines += [
            f"{PREFIX}:subcategory-{slug} a skos:Concept ;",
            f'    skos:prefLabel "{esc(slug)}"@en ;',
            f'    skos:definition "{esc(definition)}"@en ;',
            f'    skos:notation "{esc(slug)}" ;',
        ]
        for p in parents:
            if p in domain_slugs:
                lines.append(f"    skos:broader {PREFIX}:domain-{p} ;")
            else:
                print(f"  ! subcategory {slug}: parent domain '{p}' not in domains.md — skipped")
        lines.append(f"    skos:inScheme {PREFIX}:subcategory-scheme .")
        lines.append("")
    for slug, desc in tags:
        lines += [
            f"{PREFIX}:tag-{slug} a skos:Concept ;",
            f'    skos:prefLabel "{esc(slug)}"@en ;',
            f'    skos:definition "{esc(desc)}"@en ;',
            f'    skos:notation "{esc(slug)}" ;',
            f"    skos:inScheme {PREFIX}:tag-scheme .",
            "",
        ]

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        f.write("\n".join(lines))
    print(f"✓ wrote {OUT} — {len(domains)} domains, {len(subcats)} subcategories, {len(tags)} tags")


if __name__ == "__main__":
    main()
